# Generated by Django 5.2.5 on 2025-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_category_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
