# Generated by Django 5.2.5 on 2025-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_products_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
